
module.exports={
  simple:[
    {path:'/auth/signup',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
    {path:'/auth/login',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
    {path:'/auth/activate',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
    {path:'/auth/forgot',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
    {path:'/auth/reset',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
    {path:'/auth/profile',
    right:{create:true , read:true,update:true,delete:true,deny:false}},
  ],
  admin:[
    
    {path:'/user/insert-user',
    right:{create:true ,read:true,update:true,delete:true, deny:false}},
    {path:'/user/',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/list-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/update-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/assign-privilages',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/remove-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},


    {path:'/role/insert-role',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/role/list-role',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/role/get-role',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/role/update-role',
    right:{create:true , read:true,update:true,delete:true, deny:false,}
    },
    {path:'/role/delete-role',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },


    {path:'/resource/insert-resource',
    right:{create:false , read:true,update:true,delete:true, deny:false},
    },
    {path:'/resource/list-resource',
    right:{create:false , read:true,update:true,delete:true, deny:false},
    },
    {path:'/resource/defaultResources',
    right:{create:false , read:true,update:true,delete:true, deny:false},
    },

    {path:'/invoice/insert-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-single-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-customers-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/branch/insert-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/get-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/get-branchs',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/patch-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/remove-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },  
      {path:'/bill/insert-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/get-single-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/insert-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/patch-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/remove-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/supplier/insert-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-suppliers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/patch-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/remove-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/item/insert-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-items',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/patch-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/remove-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/organization/get-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/organization/patch-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/organization/remove-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/purchase-order/insert-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/get-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/list-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/convert-to-bill',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/update-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/remove-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

    {path:'/sale-order/insert-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/get-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/list-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/convert-to-invoice',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/update-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/remove-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/warehouse/insert-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/get-single-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/get-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/patch-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/remove-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    
    {path:'/reports/quantity-on-hand',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/quantity-to-recive',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/saleorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/invoices',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/purchaseorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/bills',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-sale',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-purchase',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

  ],

  warehouseManager:[
    
    {path:'/user/insert-user',
    right:{create:true ,read:true,update:true,delete:true, deny:false}},
    {path:'/user/',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/list-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/update-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/assign-privilages',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/remove-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},


    {path:'/role/insert-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/list-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/get-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/update-role',
    right:{create:true , read:true,update:true,delete:true, deny:true,}
    },
    {path:'/role/delete-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },


    {path:'/resource/insert-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/list-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/defaultResources',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },

    {path:'/invoice/insert-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-single-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-customers-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/branch/insert-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/get-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/get-branchs',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/patch-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/remove-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },  

      {path:'/bill/insert-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/get-single-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/insert-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/patch-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/remove-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/supplier/insert-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-suppliers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/patch-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/remove-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/item/insert-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-items',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/patch-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/remove-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/organization/get-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/organization/patch-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/organization/remove-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/purchase-order/insert-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/get-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/list-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/convert-to-bill',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/update-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/remove-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

    {path:'/sale-order/insert-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/get-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/list-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/convert-to-invoice',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/update-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/remove-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/warehouse/insert-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/get-single-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/get-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/patch-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/remove-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    
    {path:'/reports/quantity-on-hand',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/quantity-to-recive',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/saleorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/invoices',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/purchaseorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/bills',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-sale',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-purchase',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

  ],

  branchManager:[
    {path:'/user/insert-user',
    right:{create:true ,read:true,update:true,delete:true, deny:false}},
    {path:'/user/',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/list-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/update-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/assign-privilages',
    right:{create:true , read:true,update:true,delete:true, deny:false}},
    {path:'/user/remove-users',
    right:{create:true , read:true,update:true,delete:true, deny:false}},


    {path:'/role/insert-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/list-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/get-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/update-role',
    right:{create:true , read:true,update:true,delete:true, deny:true,}
    },
    {path:'/role/delete-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },


    {path:'/resource/insert-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/list-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/defaultResources',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },

    {path:'/invoice/insert-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-single-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-customers-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/branch/insert-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/get-branch',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/get-branchs',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/branch/patch-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/remove-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },  

      {path:'/bill/insert-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/get-single-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/insert-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/get-customers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/patch-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/remove-customer',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/supplier/insert-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/get-suppliers',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/patch-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/supplier/remove-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/item/insert-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-items',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/patch-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/remove-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },

      {path:'/organization/get-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/organization/patch-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/organization/remove-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/purchase-order/insert-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/get-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/list-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/convert-to-bill',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/update-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/remove-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

    {path:'/sale-order/insert-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/get-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/list-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/convert-to-invoice',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/update-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/remove-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/warehouse/insert-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/get-single-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/get-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/warehouse/patch-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/remove-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    
    {path:'/reports/quantity-on-hand',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/quantity-to-recive',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/saleorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/invoices',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/purchaseorders',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/bills',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-sale',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/reports/specific-item-purchase',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

  ],

 salesPerson:[
    
    {path:'/user/insert-user',
    right:{create:true ,read:true,update:true,delete:true, deny:true}},
    {path:'/user/',
    right:{create:true , read:true,update:true,delete:true, deny:true}},
    {path:'/user/list-users',
    right:{create:true , read:true,update:true,delete:true, deny:true}},
    {path:'/user/update-users',
    right:{create:true , read:true,update:true,delete:true, deny:true}},
    {path:'/user/assign-privilages',
    right:{create:true , read:true,update:true,delete:true, deny:true}},
    {path:'/user/remove-users',
    right:{create:true , read:true,update:true,delete:true, deny:true}},


    {path:'/role/insert-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/list-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/get-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/role/update-role',
    right:{create:true , read:true,update:true,delete:true, deny:true,}
    },
    {path:'/role/delete-role',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },


    {path:'/resource/insert-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/list-resource',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },
    {path:'/resource/defaultResources',
    right:{create:false , read:true,update:true,delete:true, deny:true},
    },

    {path:'/invoice/insert-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-single-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/invoice/get-customers-invoice',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },

      {path:'/branch/insert-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/get-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/get-branchs',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/patch-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/branch/remove-branch',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },  
      {path:'/bill/insert-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/get-single-bill',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/bill/change-status',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/customer/insert-customer',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/customer/get-customer',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/customer/get-customers',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/customer/patch-customer',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/customer/remove-customer',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },

      {path:'/supplier/insert-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/supplier/get-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/supplier/get-suppliers',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/supplier/patch-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/supplier/remove-supplier',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },

      {path:'/item/insert-item',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/item/get-item',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/get-items',
      right:{create:true , read:true,update:true,delete:true, deny:false},
      },
      {path:'/item/patch-item',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },
      {path:'/item/remove-item',
      right:{create:true , read:true,update:true,delete:true, deny:true},
      },

      {path:'/organization/get-organization',
      right:{create:true , read:true,update:true,delete:true, deny:false}
      },
      {path:'/organization/patch-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/organization/remove-organization',
      right:{create:true , read:true,update:true,delete:true, deny:true}
      },
      {path:'/purchase-order/insert-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/get-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/list-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/convert-to-bill',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/update-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },
    {path:'/purchase-order/remove-PO',
    right:{create:true , read:true,update:true,delete:true, deny:false},
    },

    {path:'/sale-order/insert-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/get-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/list-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/convert-to-invoice',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/update-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/sale-order/remove-SO',
    right:{create:true , read:true,update:true,delete:true, deny:false}
    },
    {path:'/warehouse/insert-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/get-single-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/get-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/patch-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/warehouse/remove-warehouse',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    
    {path:'/reports/quantity-on-hand',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/quantity-to-recive',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/saleorders',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/invoices',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/purchaseorders',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/bills',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/specific-item-sale',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },
    {path:'/reports/specific-item-purchase',
    right:{create:true , read:true,update:true,delete:true, deny:true},
    },

  ],


}
